In [1]:
import numpy as np

In [73]:
class LinearRegression:
    
    def __init__(self, fit_intercept=True):
        self.coef_ = None
        self.intercept_ = None
        self._fit_intercept = fit_intercept

    
    def fit(self, X, y):
        """Fit model coefficients.

        Arguments:
        X -- 1D or 2D numpy array 
        y -- 1D numpy array
        """
        
        # check if X is 1D or 2D array
        if len(X.shape) == 1:
            X = X.reshape(-1,1)
            
        # add bias if fit_intercept
        if self._fit_intercept:
            X = np.c_[np.ones(X.shape[0]), X]
        
        # closed form solution
        xTx = np.dot(X.T, X)
        inverse_xTx = np.linalg.inv(xTx)
        xTy = np.dot(X.T, y)
        coef = np.dot(inverse_xTx, xTy)
        
        # set attributes
        if self._fit_intercept:
            self.intercept_ = coef[0]
            self.coef_ = coef[1:]
        else:
            self.intercept_ = 0
            self.coef_ = coef
            
    def predict(self, X):
        """Output model prediction.

        Arguments:
        X -- 1D or 2D numpy array 
        """
        # check if X is 1D or 2D array
        if len(X.shape) == 1:
            X = X.reshape(-1,1) 
        return np.dot(X, self.coef_) + self.intercept_
           

In [141]:
class Metrics:
    
    def mean_squared_error(self, y_true, y_predicted):
        error = np.subtract(y_true, y_predicted)
        squared_error = error ** 2
        return np.mean(squared_error)
    
    def root_mean_squared_error(self, y_true, y_predicted):
        return np.sqrt(mean_squared_error)
        
    def mean_absolute_error(self, y_true, y_predicted):
        error = np.subtract(y_true, y_predicted)
        abs_error = np.abs(error)
        return np.mean(abs_error)

In [142]:
class MachineLearning(LinearRegression, Metrics):
    
    def __init__(self, fit_intercept=True):
        self.coef_ = None
        self.intercept_ = None
        self._fit_intercept = fit_intercept

In [143]:
ml = MachineLearning()

In [144]:
ml.fit(data, target)

In [145]:
target[:10]

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,  18.9])

In [146]:
ml.mean_squared_error(target, ml.predict(data))

21.897779217687496

In [147]:
ml.mean_absolute_error(target, ml.predict(data))

3.2729446379970861

In [148]:
ml.root_mean_squared_error(target, ml.predict(data))

AttributeError: 'function' object has no attribute 'sqrt'

In [26]:
class LinearRegression(MachineLearning):
    
    def __init__(self, fit_intercept=True):
        self.coef_ = None
        self.intercept_ = None
        self._fit_intercept = fit_intercept

    
    def fit(self, X, y):
        """Fit model coefficients.

        Arguments:
        X -- 1D or 2D numpy array 
        y -- 1D numpy array
        """
        
        # check if X is 1D or 2D array
        if len(X.shape) == 1:
            X = X.reshape(-1,1)
            
        # add bias if fit_intercept
        if self._fit_intercept:
            X = np.c_[np.ones(X.shape[0]), X]
        
        # closed form solution
        xTx = np.dot(X.T, X)
        inverse_xTx = np.linalg.inv(xTx)
        xTy = np.dot(X.T, y)
        coef = np.dot(inverse_xTx, xTy)
        
        # set attributes
        if self._fit_intercept:
            self.intercept_ = coef[0]
            self.coef_ = coef[1:]
        else:
            self.intercept_ = 0
            self.coef_ = coef
            
    def predict(self, X):
        """Output model prediction.

        Arguments:
        X -- 1D or 2D numpy array 
        """
        # check if X is 1D or 2D array
        if len(X.shape) == 1:
            X = X.reshape(-1,1) 
        return np.dot(X, self.coef_) + self.intercept_

## Testing

In [3]:
from sklearn.datasets import load_boston
boston = load_boston()
data = boston.data
target = boston.target

In [27]:
lr = LinearRegression(fit_intercept=True)
lr.fit(data, target)

In [28]:
lr.coef_

array([ -1.07170557e-01,   4.63952195e-02,   2.08602395e-02,
         2.68856140e+00,  -1.77957587e+01,   3.80475246e+00,
         7.51061703e-04,  -1.47575880e+00,   3.05655038e-01,
        -1.23293463e-02,  -9.53463555e-01,   9.39251272e-03,
        -5.25466633e-01])

In [29]:
lr.intercept_

36.491103280352945

In [31]:
lr.metrics.mean_squared_error(target, lr.predict(data))

21.897779217687496

In [34]:
from sklearn.linear_model import LinearRegression
lrsk = LinearRegression(fit_intercept=True)
lrsk.fit(data, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [35]:
lrsk.coef_

array([ -1.07170557e-01,   4.63952195e-02,   2.08602395e-02,
         2.68856140e+00,  -1.77957587e+01,   3.80475246e+00,
         7.51061703e-04,  -1.47575880e+00,   3.05655038e-01,
        -1.23293463e-02,  -9.53463555e-01,   9.39251272e-03,
        -5.25466633e-01])

In [36]:
lrsk.intercept_

36.491103280363134

In [130]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [38]:
mean_squared_error(target, lrsk.predict(data))

21.8977792176875

In [131]:
mean_absolute_error(target, lrsk.predict(data))

3.2729446379969089

In [132]:
np.sqrt(mean_squared_error(target, lrsk.predict(data)))

4.6795063006355164